#!/bin/bash

function test_introduction() {
  echo "🧪 Testing 'ksail'"
  ./ksail >/dev/null || {
    echo "❌ Testing 'ksail' failed"
    exit 1
  }
  echo "✅ Testing 'ksail' passed"
}

function test_help_flag() {
  echo "🧪 Testing 'ksail -h'"
  ./ksail -h >/dev/null || {
    echo "❌ Testing 'ksail -h' failed"
    exit 1
  }
  echo "✅ Testing 'ksail -h' passed"

  echo "🧪 Testing 'ksail up'"
  ./ksail up >/dev/null || {
    echo "❌ Testing 'ksail up' failed"
    exit 1
  }
  echo "✅ Testing 'ksail up' passed"

  echo "🧪 Testing 'ksail up -h'"
  ./ksail up -h >/dev/null || {
    echo "❌ Testing 'ksail up -h' failed"
    exit 1
  }
  echo "✅ Testing 'ksail up -h' passed"

  echo "🧪 Testing 'ksail up k3d -h'"
  ./ksail up k3d -h >/dev/null || {
    echo "❌ Testing 'ksail up k3d -h' failed"
    exit 1
  }
  echo "✅ Testing 'ksail up k3d -h' passed"

  echo "🧪 Testing 'ksail up talos -h'"
  ./ksail up talos -h >/dev/null || {
    echo "❌ Testing 'ksail up talos -h' failed"
    exit 1
  }
  echo "✅ Testing 'ksail up talos -h' passed"

  echo "🧪 Testing 'ksail down'"
  ./ksail down >/dev/null || {
    echo "❌ Testing 'ksail down' failed"
    exit 1
  }
  echo "✅ Testing 'ksail down' passed"

  echo "🧪 Testing 'ksail down -h'"
  ./ksail down -h >/dev/null || {
    echo "❌ Testing 'ksail down -h' failed"
    exit 1
  }
  echo "✅ Testing 'ksail down -h' passed"

  echo "🧪 Testing 'ksail down k3d -h'"
  ./ksail down k3d -h >/dev/null || {
    echo "❌ Testing 'ksail down k3d -h' failed"
    exit 1
  }
  echo "✅ Testing 'ksail down k3d -h' passed"

  echo "🧪 Testing 'ksail down talos -h'"
  ./ksail down talos -h >/dev/null || {
    echo "❌ Testing 'ksail down talos -h' failed"
    exit 1
  }
  echo "✅ Testing 'ksail down talos -h' passed"

  echo "🧪 Testing 'ksail install'"
  ./ksail install >/dev/null || {
    echo "❌ Testing 'ksail install' failed"
    exit 1
  }
  echo "✅ Testing 'ksail install' passed"

  echo "🧪 Testing 'ksail install -h'"
  ./ksail install -h >/dev/null || {
    echo "❌ Testing 'ksail install -h' failed"
    exit 1
  }
  echo "✅ Testing 'ksail install -h' passed"
}

function test_version_flag() {
  echo "🧪 Testing 'ksail -v'"
  ./ksail -v >/dev/null || {
    echo "❌ Testing 'ksail -v' failed"
    exit 1
  }
  echo "✅ Testing 'ksail -v' passed"
}

function test_install() {
  echo "🧪 Testing 'ksail install k3d'"
  ./ksail install k3d >/dev/null || {
    echo "❌ Testing 'ksail install k3d' failed"
    exit 1
  }
  echo "✅ Testing 'ksail install k3d' passed"

  echo "🧪 Testing 'ksail install talos'"
  ./ksail install talos >/dev/null || {
    echo "❌ Testing 'ksail install talos' failed"
    exit 1
  }
  echo "✅ Testing 'ksail install talos' passed"
}

function test_up() {
  echo "🧪 Testing 'ksail up k3d -n test'"
  ./ksail up k3d -n test || {
    echo "❌ Testing 'ksail up k3d -n test' failed"
    exit 1
  }
  echo "✅ Testing 'ksail up k3d -n test' passed"
}

function test_down() {
  echo "🧪 Testing 'ksail down k3d -n test'"
  ./ksail down k3d -n test >/dev/null 2>&1 || {
    echo "❌ Testing 'ksail down k3d -n test' failed"
    exit 1
  }
  echo "✅ Testing 'ksail down k3d -n test' passed"
}

# Run all the tests
function run_tests() {
  test_introduction
  test_help_flag
  test_version_flag
  test_install
  test_up
  test_down
  test_validate
  test_verify
}

pushd "$(dirname "$0")" >/dev/null || exit
run_tests
